# 生产环境：使用预构建镜像
services:
  navicat:
    image: ghcr.io/shidai567/navicat-docker-vnc:latest
    container_name: navicat
    ports:
      - 5800:5800 # Web GUI
    volumes:
      - ./data:/config
    environment:
      - HOME=/config
      - TZ=Asia/Shanghai
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - KEEP_APP_RUNNING=1
      - VNC_PASSWORD=${VNC_PASSWORD:-navicat}
    restart: unless-stopped
